services:
  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config:/app/config
    networks:
      - meekyolo-net
    depends_on:
      api_service:
        condition: service_healthy
      model_service:
        condition: service_healthy
      analysis_service:
        condition: service_healthy
      cloud_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  api_service:
    container_name: api_service
    build: 
      context: .
      dockerfile: api_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config:/app/config
    networks:
      - meekyolo-net
    depends_on:
      model_service:
        condition: service_healthy
      analysis_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

  model_service:
    container_name: model_service
    build: 
      context: .
      dockerfile: model_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config:/app/config
      - ./models:/app/models
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

  analysis_service:
    container_name: analysis_service
    build: 
      context: .
      dockerfile: analysis_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./results:/app/results
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

  cloud_service:
    container_name: cloud_service
    build: 
      context: .
      dockerfile: cloud_service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    volumes:
      - ./config:/app/config
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 10s

networks:
  meekyolo-net:
    driver: bridge

volumes:
  models:
  results: