services:
  gateway-service:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    image: meekyolo/gateway-service:latest
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static
      - ../config:/app/config
    environment:
      - GATEWAY_SERVICE_ENV=production
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
      - CONFIG_PATH=/app/config/config.yaml
      - API_SERVICE_URL=http://api-service:8001
      - ANALYSIS_SERVICE_URL=http://analysis-service:8002
      - MODEL_SERVICE_URL=http://model-service:8003
      - CLOUD_SERVICE_URL=http://cloud-service:8004
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  meekyolo-net:
    name: meekyolo-net
    external: true 