# 服务基础配置
PROJECT_NAME: "MeekYolo Cloud Service"
VERSION: "1.0.0"

# 服务配置
SERVICE:
  host: "0.0.0.0"
  port: 8004
  base_url: "http://cloud-service:8004"

# 数据库配置
DATABASE:
  url: "sqlite:///data/cloud_market.db"

# 存储配置
STORAGE:
  base_dir: "models"
  max_size: 1073741824  # 1GB
  allowed_formats: [".pt", ".pth", ".onnx", ".yaml"]

# 日志配置
LOGGING:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"