"""Add description column to user_nodes table

Revision ID: c78661541a4c
Revises: 0268ad47e39d
Create Date: 2025-04-10 10:34:39.705545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c78661541a4c'
down_revision: Union[str, None] = '0268ad47e39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_nodes', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('user_nodes', 'description')
    # ### end Alembic commands ###
