"""Add registered_services table

Revision ID: f245ac21ac37
Revises: 39e57080fada
Create Date: 2025-04-10 13:16:40.425049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f245ac21ac37'
down_revision: Union[str, None] = '39e57080fada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('last_status_change', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_registered_services_name')
    )
    op.create_index(op.f('ix_registered_services_name'), 'registered_services', ['name'], unique=True)
    op.create_index(op.f('ix_registered_services_status'), 'registered_services', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_services_status'), table_name='registered_services')
    op.drop_index(op.f('ix_registered_services_name'), table_name='registered_services')
    op.drop_table('registered_services')
    # ### end Alembic commands ###
