services:
  redis:
    image: redis:7.2-alpine
    container_name: analysis_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 123456
    restart: unless-stopped
    networks:
      - analysis-net

volumes:
  redis_data:
    name: analysis_redis_data

networks:
  analysis-net:
    name: analysis-net
