services:
  mysql:
    image: mysql:8.0
    container_name: api-service-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=api_service
      - MYSQL_USER=meekyolo
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "meekyolo", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api-service:
    build:
      context: ..
      dockerfile: api_service/Dockerfile
    image: meekyolo/api-service:latest
    container_name: api-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ../config:/app/config
    environment:
      - API_SERVICE_ENV=production
      - HOST=0.0.0.0
      - PORT=8001
      - WORKERS=1
      - ANALYSIS_SERVICE_URL=http://analysis-service:8002
      - MODEL_SERVICE_URL=http://model-service:8003
      - CONFIG_PATH=/app/config/config.yaml
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=meekyolo
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=api_service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  meekyolo-net:
    name: meekyolo-net
    external: true

volumes:
  mysql_data: 