services:
  cloud-service:
    build:
      context: ..
      dockerfile: cloud_service/Dockerfile
    image: meekyolo/cloud-service:latest
    container_name: cloud-service
    restart: unless-stopped
    ports:
      - "8004:8004"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ../config:/app/config
    environment:
      - CLOUD_SERVICE_ENV=production
      - HOST=0.0.0.0
      - PORT=8004
      - WORKERS=1
      - CONFIG_PATH=/app/config/config.yaml
    networks:
      - meekyolo-net
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

networks:
  meekyolo-net:
    name: meekyolo-net
    external: true 