# 服务基础配置
PROJECT_NAME: "MeekYolo Analysis Service"
VERSION: "1.0.0"

# 服务配置
SERVICE:
  host: "0.0.0.0"
  port: 8002

# 模型服务配置
MODEL_SERVICE:
  url: "http://model-service:8003"
  api_prefix: "/api/v1"

# 存储配置
STORAGE:
  base_dir: "data"
  model_dir: "data/models"
  temp_dir: "data/temp"

# 设备配置
DEVICE:
  type: "cuda"  # 或 "cpu"

# 日志配置
LOGGING:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 