# 基础配置
PROJECT_NAME: "MeekYolo Service"
VERSION: "1.0.0"

# 服务配置
SERVICES:
  model:
    host: "localhost"
    port: 8002
  analysis:
    host: "localhost"
    port: 8003
  api:
    host: "localhost"
    port: 8001
  gateway:
    host: "localhost"
    port: 8000
  cloud:
    host: "localhost"
    port: 8004

# 存储配置
STORAGE:
  base_dir: "models"  # 模型目录
  model_dir: "models"  # 模型目录
  temp_dir: "temp"
  max_size: 1073741824  # 1GB
  allowed_formats: [".pt", ".pth", ".onnx", ".yaml"]

# 分析配置
ANALYSIS:
  confidence: 0.1  # 目标检测置信度阈值,低于此值的检测框将被过滤
  iou: 0.45  # 非极大值抑制的IOU阈值,用于去除重叠检测框
  max_det: 300  # 每张图像最大检测目标数量
  device: "auto"  # 推理设备,auto表示自动选择可用的最佳设备(CPU/GPU)

# 输出配置
OUTPUT:
  save_dir: "results"
  save_img: true
  save_txt: false

# 日志配置
LOGGING:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
