# 项目基础配置
PROJECT_NAME: "MeekYolo"
VERSION: "1.0.0"

# 网关服务配置
SERVICE:
  host: "0.0.0.0"
  port: 8000

# 服务发现配置
DISCOVERY:
  interval: 30  # 服务发现间隔(秒)
  timeout: 5    # 请求超时时间(秒)
  retry: 3      # 重试次数

# 服务列表配置
SERVICES:
  api:
    url: "http://api-service:8001"
    description: "API服务"
  analysis:
    url: "http://analysis-service:8002"
    description: "分析服务"
  model:
    url: "http://model-service:8003"
    description: "模型服务"
  cloud:
    url: "http://cloud-service:8004"
    description: "云服务"
