# 服务基础配置
PROJECT_NAME: "MeekYolo Model Service"
VERSION: "1.0.0"

# 服务配置
SERVICE:
  host: "0.0.0.0"
  port: 8003

# 数据库配置
DATABASE:
  url: "sqlite:///data/model_service.db"

# 存储配置
STORAGE:
  base_dir: "models"
  max_size: 1073741824  # 1GB
  allowed_formats: [".pt", ".pth", ".onnx", ".yaml"]

# 日志配置
LOGGING:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 云服务配置
CLOUD_SERVICE:
  url: "http://localhost:8004"
  api_prefix: "/api/v1"