# 基础配置
PROJECT_NAME: "Model Service"
VERSION: "1.0.0"

# 服务配置
SERVICE:
  host: "0.0.0.0"
  port: 8003

# 数据库配置
DATABASE:
  url: "sqlite:///data/model_service.db"

# 市场配置
MARKET:
  base_url: "http://cloud-service:8004"

# 存储配置
STORAGE:
  base_dir: "models"
  temp_dir: "temp"
  max_size: 1073741824  # 1GB
  allowed_formats: [".pt", ".pth", ".onnx", ".yaml"]
# 应用配置
APP:
  title: "Model Service"
  version: "1.0.0"
  description: "模型服务"
  base_url: "http://model-service:8003"  # 添加基础URL