# 服务基础配置
PROJECT:
  name: MeekYOLO
  version: 0.3.0

# 服务配置
API_SERVICE:
  host: 0.0.0.0
  port: 8001
  url: http://localhost:8001

# 通信模式配置，支持 http 或 mqtt
COMMUNICATION:
  mode: http  # http 或 mqtt

# MQTT配置
MQTT:
  broker_host: mqtt.yingzhu.net  # MQTT Broker主机地址
  broker_port: 1883              # MQTT Broker端口
  username: yolo                 # MQTT用户名
  password: yolo                 # MQTT密码
  client_id: api_service         # MQTT客户端ID前缀，会追加随机字符
  topic_prefix: yolo/            # MQTT主题前缀
  keepalive: 60                  # 保活时间(秒)
  qos: 1                         # QoS等级

# 数据库配置
DATABASE:
  url: mysql+pymysql://root:123456@localhost/api_service?charset=utf8mb4
  echo: false

# 默认组配置
GROUP:
  default_group_id: 1
  default_group_name: system 