# 服务基础配置
PROJECT_NAME: "MeekYolo Analysis Service"
VERSION: "1.0.0"

# 服务配置
SERVICES:
  host: "0.0.0.0"
  port: 8002

# 模型服务配置
MODEL_SERVICE:
  url: "http://model-service:8003"
  api_prefix: "/api/v1"

# 分析配置
ANALYSIS:
  confidence: 0.2
  iou: 0.45
  max_det: 300
  device: "auto"
  
  # 新增配置
  analyze_interval: 1  # 默认分析间隔
  alarm_interval: 60   # 默认报警间隔
  random_interval: [0, 0]  # 默认随机间隔范围
  push_interval: 5     # 默认推送间隔

# 存储配置
STORAGE:
  base_dir: "data"
  model_dir: "models"
  temp_dir: "temp"
  max_size: 1073741824  # 1GB

# 输出配置
OUTPUT:
  save_dir: "results"
  save_txt: false
  save_img: true
  return_base64: true 